"""add lead notes

Revision ID: 657d44f4b30c
Revises: 501d04227c1d
Create Date: 2026-06-28 19:38:43.367592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '657d44f4b30c'
down_revision: Union[str, None] = '501d04227c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('notes', sa.String(length=5000), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'notes')
    # ### end Alembic commands ###
